### ISSUE TITLE
using dvswitchsrc with v4l2loopback

### ISSUE THREAD

**Issue by nueces** [timvideos/gst-plugins-dvswitch#13]
Sorry, this is not really a issue, but I'm looking for a way to pipe the dvswitchsrc to v4l2sink, could you please provide some advise about how do that? thanks. Also I only could use the dvswitchsrc with the last version of dvswitch from Debian experimental (0.9-1.1) Ibut it have some segfaults, so I recompile it from the git version (0.9-1.2) but with that version the dvswitchsrc don't seems to work. Any advise is welcome. Thanks.

**Comment by mithro** [comment]
Take a look at https://github.com/umlaeute/v4l2loopback/wiki/Gstreamer and http://askubuntu.com/questions/139239/fake-a-webcam-using-a-video-loopback-device
